"""Reader for the frozen JSBSim vortex reference.

Deliberately does NOT import jsbsim, and nothing that imports this module may.
The reference is generated by scripts/gen_jsbsim_vortex_reference.py under a
separate interpreter and checked in, so the suite runs on a machine with no
JSBSim -- which is this project's own venv -- and reference drift shows up in
git diff rather than as a mysterious change in test results.

Kept separate from atisim/jsbsim_ref.py because that file's schema is a
derivative recovery at a trim point and this one is a set of time histories.
Both are read through exactly one parser each, so a schema change breaks in one
place instead of in every consumer.
"""

import xml.etree.ElementTree as ET
from pathlib import Path
from typing import NamedTuple

import numpy as np

REFERENCE = Path(__file__).parent / "tests" / "data" / "jsbsim_vortex_reference.xml"


class Sample(NamedTuple):
    t: float
    north: float        # m, along-track from the start point
    altitude: float     # m
    wind: np.ndarray    # (3,) NED m/s, as injected
    alpha: float        # rad, as JSBSim reported
    theta: float        # rad
    q: float            # rad/s
    Nz: float           # g, JSBSim's own normal load factor
    vtrue: float        # m/s
    elevator: float     # rad


class Initial(NamedTuple):
    """The state atisim must be STARTED from, not trimmed to.

    The two engines do not trim to the same point: JSBSim's do_simple_trim
    converges to Nz = 0.99093 rather than 1.0, which is worth about 0.05 deg of
    alpha. Driving atisim from its own trim would start the two runs at
    different angles of attack and contaminate every difference downstream with
    that offset. `vel_body` is a VECTOR for the same reason jsbsim_ref.SweepPoint
    uses one -- it makes the comparison independent of how either engine defines
    alpha and beta.
    """

    vel_body: np.ndarray   # (3,) m/s, air-relative body velocity
    omega: np.ndarray      # (3,) rad/s, body rates
    euler: np.ndarray      # (3,) rad, phi/theta/psi
    controls: np.ndarray   # (3,) rad, achieved elevator/aileron/rudder
    throttle: float


class Encounter(NamedTuple):
    case: str
    model: str            # JSBSim's model name
    aircraft: str         # the atisim REGISTRY entry to compare against
    radius_source: str    # "wingrove" or "parks"
    mach: float
    values: dict          # r0, v0, core_north, matched_altitude, mass, ...
    initial: Initial
    samples: list

    @property
    def key(self):
        return (self.case, self.radius_source)

    def window(self):
        """The samples inside one core radius of the core centre.

        A DECLARED choice, not a default buried in a caller: the same run gives
        different Fig. 8 coordinates depending on the window, so every consumer
        takes this one and none invents its own.
        """
        lo = self.values["core_north"] - self.values["r0"]
        hi = self.values["core_north"] + self.values["r0"]
        return [s for s in self.samples if lo <= s.north <= hi]

    def load_increments(self):
        """(max, min) of Nz - 1, over the core window, in g.

        Minus one because Wingrove & Bach report load CHANGES, and because
        JSBSim's own trim sits at Nz = 0.991 rather than 1.0 the reference's
        trim_Nz is used as the datum instead of a literal 1.0 -- otherwise 0.9%
        of the trim offset would be read as turbulence.
        """
        datum = self.values["trim_Nz"]
        nz = np.array([s.Nz for s in self.window()]) - datum
        return float(nz.max()), float(nz.min())

    def pitch_increments(self):
        """(max, min) of theta - theta_trim over the core window, in degrees."""
        datum = self.initial.euler[1]
        theta = np.degrees(np.array([s.theta for s in self.window()]) - datum)
        return float(theta.max()), float(theta.min())

    def entry_speed_drift(self):
        """Fractional airspeed lost between the start and the core.

        Fixed-control flight sheds speed. If the two engines reach the core at
        materially different speeds, any difference in the core response is a
        drift artifact rather than a solver result, so this is a gate.
        """
        entry = self.values["airspeed"]
        edge = self.values["core_north"] - self.values["r0"]
        reached = [s for s in self.samples if s.north >= edge]
        if not reached:
            raise ValueError(f"{self.key}: no sample reached the core")
        return abs(reached[0].vtrue - entry) / entry


class Reference(NamedTuple):
    jsbsim_version: str
    dt: float
    sample_every: float
    lead_in_radii: float
    gradient_injected: bool
    encounters: dict      # (case, radius_source) -> Encounter


def _floats(text):
    return np.array([float(v) for v in text.split()])


def load(path: Path = REFERENCE) -> Reference:
    root = ET.parse(path).getroot()
    encounters = {}
    for e in root.findall("encounter"):
        init = e.find("initial")
        encounter = Encounter(
            case=e.get("case"),
            model=e.get("model"),
            aircraft=e.get("aircraft"),
            radius_source=e.get("radius_source"),
            mach=float(e.get("mach")),
            values={v.get("name"): float(v.text) for v in e.findall("value")},
            initial=Initial(
                vel_body=_floats(init.get("vel_body")),
                omega=_floats(init.get("omega")),
                euler=_floats(init.get("euler")),
                controls=_floats(init.get("controls")),
                throttle=float(init.get("throttle")),
            ),
            samples=[
                Sample(
                    t=float(s.get("t")), north=float(s.get("north")),
                    altitude=float(s.get("altitude")),
                    wind=_floats(s.get("wind")),
                    alpha=float(s.get("alpha")), theta=float(s.get("theta")),
                    q=float(s.get("q")), Nz=float(s.get("Nz")),
                    vtrue=float(s.get("vtrue")),
                    elevator=float(s.get("elevator")),
                )
                for s in e.findall("sample")
            ],
        )
        encounters[encounter.key] = encounter
    return Reference(
        jsbsim_version=root.findtext("provenance/jsbsim_version"),
        dt=float(root.findtext("provenance/dt")),
        sample_every=float(root.findtext("provenance/sample_every")),
        lead_in_radii=float(root.findtext("provenance/lead_in_radii")),
        gradient_injected=root.findtext("provenance/gradient_injected") == "true",
        encounters=encounters,
    )
